version: '3'

services:
  xray:
    image: ghcr.io/xtls/xray-core:latest 
    container_name: xray-reality
    restart: always
    ports:
      - "5443:5443"
    volumes:
      - ./config.json:/etc/xray/config.json

